# Generated by Django 4.0.6 on 2023-09-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concentrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('iron', models.DecimalField(decimal_places=4, max_digits=7)),
                ('silicon', models.DecimalField(decimal_places=4, max_digits=7)),
                ('aluminum', models.DecimalField(decimal_places=4, max_digits=7)),
                ('calcium', models.DecimalField(decimal_places=4, max_digits=7)),
                ('sulfur', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
            options={
                'ordering': ['-year', '-month', 'name'],
                'unique_together': {('name', 'year', 'month')},
            },
        ),
    ]
