# Generated by Django 4.0.6 on 2023-10-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ore', '0002_alter_concentrate_aluminum_alter_concentrate_calcium_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concentrate',
            options={'ordering': ['-year', '-month', '-batch', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='concentrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='concentrate',
            name='batch',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterUniqueTogether(
            name='concentrate',
            unique_together={('name', 'batch', 'year', 'month')},
        ),
    ]
