# Generated by Django 4.0.6 on 2023-10-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ore', '0003_alter_concentrate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentrate',
            name='batch',
            field=models.IntegerField(),
        ),
    ]
